### ISSUE TITLE
Change naming standard from KiT_* to Type*

### ISSUE THREAD

**Issue by kkoreilly** [goki/ki#12]
KiT_* is very unidiomatic Go, as it contains an underscore and directly adjacent alternating capital letters.

**Comment by rcoreilly** [comment]
Yes!  The end user should not generally be using KiT_ types -- they are basically for internal use in writing `AddNew*` methods, for registering properties to types to customize the GUI for that object, and for the `Embed()` method to access embedded types. All of those use-cases are internal to a given package, so renaming should not have any external effects.

However, I just checked in all of `emer`: the one case where we use KiT_ is in `AddNewTab` to specify the type of thing to put in the tab (KiT_NetView or KiT_Plot2D typically).  So that would be a breaking change for all those calls, but in the new axon framework, this is mostly handled by the egui package, so most axon sims do not use KiT_ at all.

**Comment by kkoreilly** [comment]
Prefixing `KiT_*` types with `Type` instead will be much clearer to the developer and clearly convey that the values are just`reflect.Type`s. For example, `gi.TypeButton` is much clearer than `gi.KiT_Button`.

**Comment by kkoreilly** [comment]
Done in e101f4fa2608a0aac50706bc8120445f5db4d64f.
